/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "1.9.10"
    kotlin("plugin.spring") version "1.9.0"
    kotlin("plugin.jpa") version "1.9.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.0.5")
    api("org.projectlombok:lombok:1.18.26")
    api("org.springframework.boot:spring-boot-starter-test:3.0.5")
    api("org.springframework.boot:spring-boot-starter-web:3.0.5")
    api("org.springframework.boot:spring-boot-starter-security:3.0.5")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22")
    api("org.springframework:spring-web:6.0.7")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.5")
    runtimeOnly("com.h2database:h2:2.1.214")
    runtimeOnly("org.postgresql:postgresql:42.5.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.8.22")
}

group = "hulio13"
version = "0.0.1-SNAPSHOT"
description = "articles-api"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(17)
}