server:
  port: 8080
  address: localhost

spring:
  application:
    name: articles-api

  security:
    user:
      name: ${ADMIN_NAME}
      password: ${ADMIN_PASS}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    generate-ddl: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true

logging:
  level:
    root: info