server:
  port: 8080
  address: localhost

spring:
  application:
    name: articles-api

  security:
    user:
      name: "admin"
      password: "somePass"

  datasource:
    url: jdbc:postgresql://localhost:5432/articles_api
    username: "articles_api_user"
    password: "someStrongPass"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

    open-in-view: false
    generate-ddl: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true

logging:
  level:
    root: info